#ifndef MAYA_PYTHON_C_EXT_STATUSES_H
#define MAYA_PYTHON_C_EXT_STATUSES_H

#include <limits.h>


enum MayaPythonCExtStatus
{
	UNKNOWN_FAILURE = -1,
	NODE_DOES_NOT_EXIST = -2,
	UNABLE_TO_GET_ACTIVE_SELECTION = -3,
	UNABLE_TO_SET_ACTIVE_SELECTION = -4,
	UNABLE_TO_MERGE_SELECTION_LISTS = -5,
	SUCCESS = 0
};


#endif /* MAYA_PYTHON_C_EXT_STATUSES_H */
